#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct  4 17:34:26 2019
Easy ways to create .json files with chesXNet as example
@author: nyamewaa
"""
import csv
import json

csv_name = 'BBox_List_2017.csv'; #put in the name of your csv
csv_path = './csv_xx`x`name' #if file is in a different directory you can replace csv_name with csv_path
json_path = './json'


#%% Method 1
with open(csv_name) as f:
    reader = csv.DictReader(f)
    rows = list(reader)

with open('chesXNet_BBox.json', 'w') as f:
    json.dump(rows, f, indent = 4)
    

#%% Method 2
csvfile = open(csv_name, 'r')
jsonfile = open('chesXNet3.json', 'w')

#no field names needed since the header is on the first row in 
#the file,otherwise this would have been specified as below
#fieldnames = ("FirstName","LastName","IDNumber","Message") 
#reader = csv.DictReader( csvfile, fieldnames)
reader = csv.DictReader( csvfile)
for row in reader:
    json.dump(row, jsonfile)
    jsonfile.write('\n')



